# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29e6a7b9a0935fe2ba1c019af62424594ffb42ad03b2074504b7a8f1e5594bbbbc133be579350b52ede7bbcceb1cca3ef0bd69ff9df93e548a32178349d160d9

test:
  secret_key_base: 7903613bd639da868a14b6157136374b579053a2105b3ef50ee9eafba3c8636caad7dfeedfd18e93e8477c85c763f522ac6804a1f0381601775d694a6c6f799a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
